name: build-and-deploy

on:
  push:
    tags:
      - 'v*-khub'   # e.g., v1.0.0

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  OWNER: ${{ github.repository_owner }}
  REPO:  ${{ github.event.repository.name }}
  TAG:   ${{ github.ref_name }}  # the tag (e.g., v1.0.0)

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        site: [khub]
    steps:
      - uses: actions/checkout@v4

      - name: Compute lowercase owner/repo
        shell: bash
        run: |
          owner="${GITHUB_REPOSITORY_OWNER,,}"
          repo="${GITHUB_REPOSITORY##*/}"
          repo="${repo,,}"
          echo "OWNER_LC=$owner" >> $GITHUB_ENV
          echo "REPO_LC=$repo" >> $GITHUB_ENV

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.OWNER_LC }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push image
        uses: docker/build-push-action@v6
        with:
          context: ./apps/${{ matrix.site }}
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.OWNER_LC }}/${{ env.REPO_LC }}-${{ matrix.site }}:${{ env.TAG }}
            ${{ env.REGISTRY }}/${{ env.OWNER_LC }}/${{ env.REPO_LC }}-${{ matrix.site }}:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        site: [khub]
    steps:
      - uses: actions/checkout@v4

      - name: Compute lowercase owner/repo
        shell: bash
        run: |
          owner="${GITHUB_REPOSITORY_OWNER,,}"
          repo="${GITHUB_REPOSITORY##*/}"
          repo="${repo,,}"
          echo "OWNER_LC=$owner" >> $GITHUB_ENV
          echo "REPO_LC=$repo" >> $GITHUB_ENV

      - name: Upload stack file
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          passphrase: ${{ secrets.VPS_PASSPHRASE }}
          source: deploy/stack.${{ matrix.site }}.yml
          target: /home/deploy/${{ matrix.site }}/

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          passphrase: ${{ secrets.VPS_PASSPHRASE }}
          script: |
            # login to GHCR on the server so Swarm can pull private images
            echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u "${{ secrets.GHCR_USER }}" --password-stdin

            # (optional) verify login
            docker info | grep -i "Registry"
            
            export IMAGE_NAME="${{ env.REGISTRY }}/${{ env.OWNER_LC }}/${{ env.REPO_LC }}-${{ matrix.site }}"
            export IMAGE_TAG="${{ env.TAG }}"
            docker stack deploy \
              -c /home/deploy/${{ matrix.site }}/deploy/stack.${{ matrix.site }}.yml \
              ${{ matrix.site }} --with-registry-auth