version: "3.8"

networks:
  web:
    external: true

services:
  kioart:
    image: ${IMAGE_NAME}:${IMAGE_TAG} # e.g., ghcr.io/OWNER/REPO-kioart:v1.0.0
    environment:
      - PORT=8080
    networks: [web]
    deploy:
      replicas: 2
      labels:
        - traefik.enable=true

        # Primary HTTPS router
        - traefik.http.routers.khub.rule=Host(`0xkio.com`)
        - traefik.http.routers.khub.entrypoints=websecure
        - traefik.http.routers.khub.tls=true
        - traefik.http.routers.khub.tls.certresolver=le

        # Service port inside the container
        - traefik.http.services.khub.loadbalancer.server.port=8080

        # Optional: redirect www -> apex
        - traefik.http.routers.khub-www.rule=Host(`0xkio.com`)
        - traefik.http.routers.khub-www.entrypoints=web
        - traefik.http.routers.khub-www.middlewares=khub-to-apex
        - traefik.http.middlewares.khub-to-apex.redirectregex.regex=^https?://0xkio\.com/(.*)
        - traefik.http.middlewares.khub-to-apex.redirectregex.replacement=https://0xkio.com/$$1
