version: "3.8"

networks:
  web:
    external: true

services:
  kioart:
    image: ${IMAGE_NAME}:${IMAGE_TAG} # e.g., ghcr.io/OWNER/REPO-kioart:v1.0.0
    environment:
      - PORT=8080
    networks: [web]
    deploy:
      replicas: 2
      labels:
        - traefik.enable=true

        # Primary HTTPS router
        - traefik.http.routers.kioart.rule=Host(`0xkio.com`)
        - traefik.http.routers.kioart.entrypoints=websecure
        - traefik.http.routers.kioart.tls=true
        - traefik.http.routers.kioart.tls.certresolver=le

        # Service port inside the container
        - traefik.http.services.kioart.loadbalancer.server.port=8080

        # Optional: redirect www -> apex
        - traefik.http.routers.kioart-www.rule=Host(`0xkio.com`)
        - traefik.http.routers.kioart-www.entrypoints=web
        - traefik.http.routers.kioart-www.middlewares=kioart-to-apex
        - traefik.http.middlewares.kioart-to-apex.redirectregex.regex=^https?://0xkio\.com/(.*)
        - traefik.http.middlewares.kioart-to-apex.redirectregex.replacement=https://0xkio.com/$$1